from typing import List
from pydantic import BaseModel, Field


class ReportSection(BaseModel):
    """Single section of the performance report."""

    title: str
    content: str


class LLMReportResponse(BaseModel):
    """
    Structured report generated by the Report Agent.
    """

    report_title: str = Field(
        description="Title of the report"
    )

    executive_summary: str = Field(
        description="Executive summary"
    )

    overall_status: str = Field(
        description="PASS or FAIL"
    )

    key_findings: List[str] = Field(
        default_factory=list
    )

    report_sections: List[ReportSection] = Field(
        default_factory=list
    )

    conclusion: str




# ============================================================
# Generated Report Files
# ============================================================

class GeneratedReports(BaseModel):
    """
    Stores the paths of all generated report files.
    """

    pdf_path: str = Field(
        description="Path to generated PDF report"
    )

    html_path: str = Field(
        description="Path to generated HTML report"
    )

    json_path: str = Field(
        description="Path to generated JSON report"
    )


# ============================================================
# Report Agent Response
# ============================================================

class ReportAgentResponse(BaseModel):
    """
    Final response returned by the Report Agent.
    """

    report: LLMReportResponse

    generated_reports: GeneratedReports